name: Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
        arch: [amd64, arm64]
        exclude:
          # Windows ARM64 builds require special setup, exclude for now in CI
          - platform: windows-latest
            arch: arm64
          # Ubuntu ARM64 requires cross-compilation setup
          - platform: ubuntu-latest
            arch: arm64
    
    runs-on: ${{ matrix.platform }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install Linux dependencies
      if: matrix.platform == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential pkg-config libgtk-3-dev libwebkit2gtk-4.0-dev libgio-unix-2.0-dev
    
    - name: Install Wails
      run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
    
    - name: Install frontend dependencies
      run: npm install
      working-directory: frontend
    
    - name: Build application (AMD64)
      if: matrix.arch == 'amd64'
      run: wails build
    
    - name: Build application (ARM64 - macOS only)
      if: matrix.arch == 'arm64' && matrix.platform == 'macos-latest'
      run: wails build -platform darwin/arm64
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: goask-${{ matrix.platform }}-${{ matrix.arch }}
        path: |
          build/bin/*
        retention-days: 7
