name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - platform: ubuntu-latest
            os: linux
          - platform: windows-latest
            os: windows
          - platform: macos-latest
            os: darwin
          - platform: macos-14  # macOS ARM64
            os: darwin-arm64
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Linux dependencies
      if: matrix.platform == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential pkg-config libgtk-3-dev libwebkit2gtk-4.1-dev

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache: false  # Disable cache to avoid timeout issues

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install Wails
      run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

    - name: Install frontend dependencies
      run: npm install
      working-directory: frontend

    - name: Build application
      run: wails build

    - name: Test Go modules
      run: go test ./...

    - name: Upload build artifacts (Linux)
      if: matrix.platform == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: goask-linux-amd64
        path: build/bin/goask

    - name: Upload build artifacts (Windows)
      if: matrix.platform == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: goask-windows-amd64
        path: build/bin/goask.exe

    - name: Upload build artifacts (macOS Intel)
      if: matrix.platform == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: goask-macos-amd64
        path: build/bin/goask.app

    - name: Upload build artifacts (macOS ARM64)
      if: matrix.platform == 'macos-14'
      uses: actions/upload-artifact@v4
      with:
        name: goask-macos-arm64
        path: build/bin/goask.app